image: docker:24.0.2  # Has Docker CLI installed

services:
  - docker:dind

stages:
  - test
  - build

before_script:
  - apk add --no-cache python3 py3-pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python3 manage.py test

build:
  stage: build
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USER/sana3ti-backend .
    - docker push $DOCKER_USER/sana3ti-backend
  only:
    - main
